#include "DrivePID.h"
#include "../RobotMap.h"
#include "../OI.h"
#include "SmartDashboard/SmartDashboard.h"
#include "LiveWindow/LiveWindow.h"
#include <iostream>
#include <math.h>

namespace{
 const int c_CPR = 256; //counts per revolution for encoder
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
DrivePID::DrivePID() : PIDSubsystem("DrivePID", c_straightP, c_straightI, c_straightD) {
    SetAbsoluteTolerance(0.2);

    left1 = RobotMap::drivePIDLeft1;
    left2 = RobotMap::drivePIDLeft2;
    left3 = RobotMap::drivePIDLeft3;
    leftDriveGroup = RobotMap::drivePIDLeftDriveGroup;
    right1 = RobotMap::drivePIDRight1;
    right2 = RobotMap::drivePIDRight2;
    right3 = RobotMap::drivePIDRight3;
    rightDriveGroup = RobotMap::drivePIDRightDriveGroup;
    diffDrive = RobotMap::drivePIDDiffDrive;
    leftEncoder = RobotMap::drivePIDLeftEncoder;
    rightEncoder = RobotMap::drivePIDRightEncoder;
    shifter = RobotMap::drivePIDShifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    //Comment this in if the encoder is plugged into a talon
//    right1->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, 50);
//    right1->ConfigPeakOutputReverse(-100, 50);
//    right1->ConfigPeakOutputForward(100, 50);
    right1->SetSafetyEnabled(false);
//    right1->SetStatusFramePeriod(Status_2_Feedback0_, 10, 20);

    diffDrive->SetSafetyEnabled(false);

    right2->SetSafetyEnabled(false);
    right3->SetSafetyEnabled(false);

//    left1->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, 50);
//    left1->ConfigPeakOutputReverse(-100, 50);
//    left1->ConfigPeakOutputForward(100, 50);
    left1->SetSafetyEnabled(false);
 //   left1->SetStatusFramePeriod(Status_2_Feedback0_, 10, 20);

    left2->SetSafetyEnabled(false);
    left3->SetSafetyEnabled(false);

    gyro = new AHRS(SPI::Port::kMXP, 100);

    GetPIDController()->SetContinuous(true);
    GetPIDController()->SetInputRange(-180, 180);
    GetPIDController()->SetOutputRange(-1, 1);
    GetPIDController()->SetAbsoluteTolerance(.5);

    // Use these to get going:
    // SetSetpoint() -  Sets where the PID controller should move the system
    //                  to
    // Enable() - Enables the PID controller.

    driveState = c_accelerate;
    m_newHeading = 0;

    GetPIDController()->Disable();
}

double DrivePID::ReturnPIDInput() {
    // Return your input value for the PID loop
    return GetYaw();
}

void DrivePID::UsePIDOutput(double output) {
    // Use output to drive your system, like a motor

    //rightDriveGroup->PIDWrite(output);
    //leftDriveGroup->PIDWrite(output);

}

double DrivePID::GetPIDOutput(){
	return GetPIDController()->Get();
}

void DrivePID::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
}

//Arcade Drive
void DrivePID::ArcadeDrive(double forward, double turn) {
	GetPIDController()->Disable();
	diffDrive.get()->ArcadeDrive(forward, turn);
}

//Tank Drive
void DrivePID::SetSidePower(double left, double right){
	diffDrive.get()->TankDrive(left, right);
}

//Curve using the CurvatureDrive function
void DrivePID::DriveCurve(double power, double heading) {
	SetDirection(heading);
	double correction = GetPIDController()->Get();

	std::cout << "Correction: " << correction << std::endl;
	if(heading > 0){
		diffDrive.get()->CurvatureDrive(power-correction, heading, false);
	}
	else if(heading < 0){
		diffDrive.get()->CurvatureDrive(power+correction, heading, false);
	}
	else{
		diffDrive.get()->CurvatureDrive(power-correction, heading, false);
	}
}

//Drive straight, manually applying correction
void DrivePID::DriveStraight(double power, double heading) {

	double yaw = GetYaw();
	SetDirection(heading);
	double correction = fabs(GetPIDOutput());
	bool direction;

	if(yaw > 0){
		if((heading < yaw)&& (heading > (-180 + yaw))){
			direction = 1; //Left
		}
		else{
			direction = 0;
		}
	}
	else if(yaw < 0){
		if((heading > yaw)&& (heading < (180 + yaw))){
			direction = 0; //Right
		}
		else{
			direction = 1;
		}
	}

	if((correction > 0.01) && (correction < 0.2)){
		correction = 0.2;
	}
	else if((correction > -0.2) && (correction < -0.01)){
		correction = -0.2;
	}

	std::cout << "Correction: " << correction << std::endl;

	if((power < 0) && (direction == 1)){
		diffDrive.get()->TankDrive(power+correction, power, false);
	}
	else if((power < 0) && (direction == 0)){
		diffDrive.get()->TankDrive(power, power+correction, false);
	}
	else if((power > 0) && (direction == 1)){
		diffDrive.get()->TankDrive(power+correction, power, false);
	}
	else if((power > 0) && (direction == 0)){
		diffDrive.get()->TankDrive(power, power+correction, false);
	}
	else{
		diffDrive.get()->TankDrive(power, power);
	}

}

//Rotate, manually applying correction
void DrivePID::Rotate(double heading) {

	double yaw = GetYaw();
	SetDirection(heading);
	double correction = fabs(GetPIDOutput());
	bool direction;

	if(yaw > 0){
		if((heading < yaw)  && (heading > (-180 + yaw))){
			direction = 1; //Left
		}
		else{
			direction = 0;
		}
	}
	else if(yaw < 0){
		if((heading > yaw) && (heading < (180 + yaw))){
			direction = 0; //Right
		}
		else{
			direction = 1;
		}
	}

	if((correction > 0.01) && (correction < 0.2)){
		correction = 0.2;
	}
	else if((correction > -0.2) && (correction < -0.01)){
		correction = -0.2;
	}

	std::cout << "Correction: " << correction << "  Direction :  " << direction << std::endl;

	if(direction){
		std::cout << " LEFT " << std::endl;
		diffDrive.get()->TankDrive(correction, -correction, false);
	}
	else if(!direction){
		std::cout << " RIGHT " << std::endl;
		diffDrive.get()->TankDrive(-correction, correction, false);
	}
}

//Drive a distance within two inches
void DrivePID::DriveDistance(double distance, double power, double heading){
	//double yaw = GetYaw();
	SetDirection(heading+1);

	if(driveState == c_accelerate){
		DriveAccelerate(distance, power, heading);
	}
	else if(driveState == c_deaccelerate){
		DriveDeaccelerate(distance, power);
	}
	else{
		DriveStop(power);
	}
}

//Accelerate until stopping distance
void DrivePID::DriveAccelerate(double distance, double power, double heading){
	//SetSidePower(power, power);
	DriveStraight(power, heading+1);
	double distanceDiff = fabs(fabs(GetDistance())-(fabs(distance)));

	double velocity = fabs(GetVelocity());
	double stoppingDist = velocity*1.35;

	std::cout << "Velocity: " << velocity << "   Distance Difference:  " << distanceDiff
			<< "  Stopping Distance:  " << stoppingDist << std::endl;

	if(distanceDiff <= stoppingDist){
		driveState = c_deaccelerate;
		std::cout << "  Change to Deaccelerate  " << std::endl;
	}
}

//Deaccelerate by coasting
void DrivePID::DriveDeaccelerate(double distance, double power){
	std::cout << "   Drive Deaccelerate   " << std::endl;
	SetSidePower(0, 0);
	double velocity = fabs(GetVelocity());
	if(velocity < (10)){
		std::cout << "   Change to Drive Stop    " << std::endl;
		driveState = c_stop;
	}
}

//Apply power inverse to velocity to stop
void DrivePID::DriveStop(double distance){
	double velocity = GetVelocity();
	double inverseVelocity = 1/(GetVelocity()/2);
	std::cout << "   Drive Stop   " << " Inverse Velocity:  " << inverseVelocity << std::endl;

	if(velocity > 2){
		SetSidePower(-inverseVelocity, -inverseVelocity);
	}
	else if(velocity < -2){
		SetSidePower(-inverseVelocity, -inverseVelocity);
	}
	else{
		SetSidePower(0, 0);
	}
}

//Shift to climb
void DrivePID::Shift(bool state) {
	shifter.get()->Set(state);
}

//Return right encoder value
double DrivePID::GetRightEncoder() {
	//double encoderCount = (-1)*right1->GetSensorCollection().GetQuadraturePosition();
	double encoderCount = rightEncoder->Get();
	double distance = encoderCount/c_CPR*6.05*3.1415;

	return distance;
}

//Return left encoder value
double DrivePID::GetLeftEncoder() {
	//double encoderCount = left1->GetSensorCollection().GetQuadraturePosition();
	double encoderCount = leftEncoder->Get();
	double distance = encoderCount/c_CPR*6.05*3.1415;

	return distance;
}

//Return distance traveled based on encoder values
double DrivePID::GetDistance(){
	double rightDist = GetRightEncoder()*(-1);
	double leftDist = GetLeftEncoder();
	double m_distanceTraveled;

	if(rightDist < 0 ){
		m_distanceTraveled =  (rightDist+leftDist)/2;
	}
	else if (rightDist > 0){
		m_distanceTraveled = ((rightDist+leftDist)/2)*(-1);
	}
	else{
		m_distanceTraveled = 0;
	}

	return m_distanceTraveled;
}


//Zero drive encoders
void DrivePID::ZeroEncoders(){
	//Use this if the encoders are plugged into the Roborio
	rightEncoder->Reset();
	leftEncoder->Reset();

	//Use this if the encoders are plugged into the talons
//	right1->GetSensorCollection().SetQuadraturePosition(0, 50);
//	left1->GetSensorCollection().SetQuadraturePosition(0, 50);
}

//Return yaw from gyro
float DrivePID::GetYaw(){
	return gyro->GetYaw();
}

//Zero gyro yaw
void DrivePID::ZeroYaw(){
	gyro->ZeroYaw();
}

//Set PID values
void DrivePID::SetPIDs(double kP, double kI, double kD) {
	GetPIDController()->SetPID(kP, kI, kD);
}

//Set heading setpoint for gyro and turning
void DrivePID::SetDirection(double heading){
	if(GetPIDController()->GetSetpoint() != heading)
	{
		GetPIDController()->Disable();
		GetPIDController()->Reset();

		GetPIDController()->SetSetpoint(heading); //we are now facing the same way the entire time
		GetPIDController()->Enable();
	}
}

//Turn with constantly updating Limelight data during teleop
void DrivePID::DriveTurning(double driverY){
	std::shared_ptr<NetworkTable> table = NetworkTable::GetTable("limelight");
	table->PutNumber("pipeline", 2);
	UpdateLimelight();
	float kp = -0.05f;
	float min_command = 0.05f;
	double yaw = GetYaw();
	//if yaw changes BIG wrong way, limit correction. only lock on boxes in acceptable range. back up??
	float heading_error = -m_targetX;
	float steering_adjust= 0.0f;

	if(m_targetX == 0){
		steering_adjust = driverY;
	}
	else if(m_targetX > 3){
		steering_adjust = kp*heading_error - min_command;
	}
	else if(m_targetX < -3){
		steering_adjust = kp*heading_error + min_command;
	}

	SetSidePower(driverY-steering_adjust, driverY+steering_adjust);
}

//Pull a new contour from the Limelight Data
void DrivePID::UpdateLimelight(){

	std::shared_ptr<NetworkTable> table = NetworkTable::GetTable("limelight");
	table->PutNumber("ledMode", 0);

	m_targetX = table->GetNumber("tx", 0);
	m_targetY = table->GetNumber("ty", 0);
	m_area = table->GetNumber("ta", 0);
	m_skew = table->GetNumber("ts", 0);

	std::cout << "  x: " << m_targetX << "  y: " << m_targetY << "  a:" << m_area << "  s: " << m_skew ;
	std::cout << "  Angle:  " << atan(m_targetX/76)*180/3.14 << "  Yaw: " << GetYaw() <<  std::endl;
}

//Adjust robot with data from Vision target
double DrivePID::AdjustWithVision(){

	double yaw = GetYaw();
	double adjustment = atan(m_targetX/76)*180/3.14; //76 inches

	if(m_targetX > 2){
		std::cout << " Target is too far right";
		m_newHeading = yaw+adjustment;
	}
	else if (m_targetX < -2){
		std::cout << " Target is too far left";
		m_newHeading = yaw+adjustment;
	}
	else{
		m_newHeading = yaw;
	}

	std::cout << "  Yaw: " << GetYaw() << "  New Heading:  " << m_newHeading << std::endl;
	return m_newHeading;
}

//Return X output from Limelight data
double DrivePID::OutputX(){
	return m_targetX;
}

//Check if target is found from Limelight data
bool DrivePID::IsTargetFound(){
	//UpdateLimelight();
	if((m_targetX < 5) && (m_targetX > -5) && ((m_targetY < 12) && (m_targetY > 10)) && (m_area > 8) && (m_area < 12) ){
		return true;
	}
	else{
		return false;
	}
}

//Return velocity based on encoder rates
double DrivePID::GetVelocity(){
	double encoder_LRate = leftEncoder->GetRate(); //returns ticks / second
	double encoder_RRate = rightEncoder->GetRate()*(-1); // *-1 for comp bot
	double averageEncoderRate = (encoder_LRate + encoder_RRate) / 2;
	double velocity = averageEncoderRate*6.05/c_CPR; //turns ticks / second into inches / second
	return velocity;
}

