// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELBOW_H
#define ELBOW_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
#include "ctre/phoenix.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Elbow: public frc::PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<WPI_TalonSRX> elbowRight;
	std::shared_ptr<WPI_TalonSRX> elbowLeft;
	std::shared_ptr<frc::SpeedControllerGroup> elbowRotate;
	std::shared_ptr<frc::Encoder> elbowPosition;
	std::shared_ptr<frc::DigitalInput> elbowZero;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Elbow();
	double ReturnPIDInput() override;
	void UsePIDOutput(double output) override;
	void InitDefaultCommand() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	void SetAngle(double angle);
	void ZeroDegrees();

	//Disabled the PID before setting the output speed. To re-enable the PID, call SetAnlge().
	void SetElbowSpeed(double speed);

	double GetAngle();


};

#endif
