// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Elevator.h"
#include "../RobotMap.h"
#include "SmartDashboard/SmartDashboard.h"
#include "LiveWindow/LiveWindow.h"
#include <iostream>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

namespace{
	const double heightDivisor = 317.24;
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
Elevator::Elevator() : PIDSubsystem("Elevator", 1.0, 0.0, 0.0) {
    SetAbsoluteTolerance(0.2);
   // GetPIDController()->SetContinuous(false);
 //   frc::LiveWindow::GetInstance()->AddActuator("Elevator", "PIDSubsystem Controller", GetPIDController());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
   // elevatorEncoder = RobotMap::elevatorElevatorEncoder;
    elevatorRight = RobotMap::elevatorElevatorRight;
    elevatorLeft = RobotMap::elevatorElevatorLeft;
    liftMotors = RobotMap::elevatorLiftMotors;
    elevatorZero = RobotMap::elevatorElevatorZero;
    elevatorHigh = RobotMap::elevatorElevatorHigh;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    //elevatorRight.get()->SetInverted(true);
    elevatorRight->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, 50);
    elevatorRight->ConfigPeakOutputReverse(-100, 50);
    elevatorRight->ConfigPeakOutputForward(100, 50);
    elevatorRight->SetSafetyEnabled(false);

    m_speed = 0;
    m_heightSet = false;

    // Use these to get going:
    // SetSetpoint() -  Sets where the PID controller should move the system
    //                  to
    // Enable() - Enables the PID controller.

    //Start with the PID disabled. To enable, call SetElevatorHeight()
    GetPIDController()->Disable();
}

double Elevator::ReturnPIDInput() {
    // Return your input value for the PID loop
    // e.g. a sensor, like a potentiometer:
    // yourPot->SetAverageVoltage() / kYourMaxVoltage;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
       // return elevatorEncoder->PIDGet();
	std::cout << " Being called " << std::endl;
	return GetHeight();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
}

void Elevator::UsePIDOutput(double output) {
    // Use output to drive your system, like a motor
    // e.g. yourMotor->Set(output);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
	if(m_heightSet == true){
		if(output > 0.5){
			output = 0.5;
		}
		else if (output < -0.2){
			output = -0.2;
		}

		output = output+.3;

		std::cout << "Use PID Output" << std::endl;
		elevatorRight.get()->Set(output);
		elevatorLeft.get()->Set(-output);
	}
	else{
		elevatorRight.get()->Set(0);
		elevatorLeft.get()->Set(0);
	}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
}

void Elevator::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Elevator::SetElevatorSpeed(double speed) {
	Disable();
	m_speed = speed;
	//SensorTriggered();
	std::cout << "Set ElevatorSpeed" << std::endl;
	elevatorRight.get()->Set(-m_speed);
	elevatorLeft.get()->Set(m_speed);
}

double Elevator::GetHeight(){
	double encoderCount = elevatorRight->GetSensorCollection().GetQuadraturePosition();
	double distance = encoderCount/heightDivisor;
	return distance;
}

void Elevator::SetHeight(double height){

	m_heightSet = true;

	if(GetPIDController()->GetSetpoint() != height)
	{
		GetPIDController()->Disable();
		GetPIDController()->Reset();

		std::cout << "Set HEIGHT" << std::endl;

		GetPIDController()->SetSetpoint(height);
		GetPIDController()->Enable();
	}
}

void Elevator::SensorTriggered(){
	double setValue = 71*heightDivisor;

	std::cout << " Elevator Sensor:  " << IsSensorTripped() << std::endl;
	if(IsSensorTripped()){
		elevatorRight->GetSensorCollection().SetQuadraturePosition(setValue, 50);
	}
}

bool Elevator::IsSensorTripped(){
	return !elevatorZero.get()->Get();
}

void Elevator::ZeroHeight(){
	elevatorRight->GetSensorCollection().SetQuadraturePosition(0, 50);
}
