// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoDistance.h"
#include <cmath>
#include <iostream>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoDistance::AutoDistance(double distance, double power, double heading, double timeout): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::drivePID.get());

	m_distance = distance;
	m_power = power;
	m_distanceTraveled = 0;
	m_commandActive = true;
	m_heading = heading;

	if(!timeout == 0){
		SetTimeout(timeout);
	}

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoDistance::Initialize() {
	Robot::drivePID->SetPIDs(c_straightP, c_straightI, c_straightD);
	Robot::drivePID.get()->ZeroEncoders();
	Robot::elevator.get()->SetElevatorSpeed(0);
	Robot::drivePID.get()->SetDirection(m_heading);
	Robot::drivePID.get()->driveState = 0; //0 = c_accelerate in DrivePID
}

// Called repeatedly when this Command is scheduled to run
void AutoDistance::Execute() {

	Robot::drivePID->DriveDistance(m_distance, m_power, m_heading);

	m_distanceTraveled = Robot::drivePID.get()->GetDistance();
	double velocity = Robot::drivePID.get()->GetVelocity();

}

// Make this return true when this Command no longer needs to run execute()
bool AutoDistance::IsFinished() {
	double velocity = fabs(Robot::drivePID.get()->GetVelocity());

	if((velocity < 0.5) && (Robot::drivePID.get()->driveState == 2)){
		return true;
	}
	else if(IsTimedOut()){
		return true;
	}
	else{
		return false;
	}

}

// Called once after isFinished returns true
void AutoDistance::End() {
	Robot::drivePID->SetSidePower(0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoDistance::Interrupted() {

}


