// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoRotate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoRotate::AutoRotate(double rotate): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::drivePID.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_rotate = rotate;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoRotate::Initialize() {
	Robot::drivePID.get()->ZeroYaw();
}

// Called repeatedly when this Command is scheduled to run
void AutoRotate::Execute() {
	Robot::drivePID.get()->Rotate(m_rotate);
}

// Make this return true when this Command no longer needs to run execute()
bool AutoRotate::IsFinished() {

	if((fabs(m_rotate) <  fabs(Robot::drivePID->GetYaw()))){

			return true;
		}
		else{
				return false;
		}
}

// Called once after isFinished returns true
void AutoRotate::End() {
	Robot::drivePID.get()->ArcadeDrive(0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoRotate::Interrupted() {

}
