// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoDriveWithVisionL.h"
#include <cmath>
#include <iostream>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoDriveWithVisionL::AutoDriveWithVisionL(double distance, double power, double timeout): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::drivePID.get());

	m_power = power;
	m_distance = distance;
	m_rotate = 0;
	m_distanceTraveled = 0;

	if(timeout != 0)
	{
		SetTimeout(timeout);
	}
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoDriveWithVisionL::Initialize() {
	Robot::drivePID->SetPIDs(c_straightP, c_straightI, c_straightD);
	Robot::drivePID.get()->ZeroEncoders();
	Robot::drivePID.get()->UpdateLimelight();
	m_rotate = 2.5*Robot::drivePID->AdjustWithVision();
	if(m_rotate > 0 ){
		m_distance = -5*Robot::drivePID->AdjustWithVision();
	}
	else{
		m_distance = 5*Robot::drivePID->AdjustWithVision();
	}


}

// Called repeatedly when this Command is scheduled to run
void AutoDriveWithVisionL::Execute() {
	Robot::drivePID->DriveStraight(m_power, m_rotate);
	m_distanceTraveled = Robot::drivePID->GetDistance();
}

// Make this return true when this Command no longer needs to run execute()
bool AutoDriveWithVisionL::IsFinished() {
	double yaw = Robot::drivePID.get()->GetYaw();

	if(((m_rotate + 5) > yaw) && ((m_rotate - 5) < yaw)){
		std::cout << " FINAL: " << fabs(Robot::drivePID->GetYaw()) << std::endl;
		return true;
	}
	else if(IsTimedOut()){
		std::cout << "  3  " << std::endl;
		return true;
	}
	else{
		return false;
	}
}

// Called once after isFinished returns true
void AutoDriveWithVisionL::End() {
	Robot::drivePID->ArcadeDrive(0, 0);
	Robot::drivePID.get()->ZeroEncoders();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoDriveWithVisionL::Interrupted() {

}
