// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTO_DISTANCE_H
#define AUTO_DISTANCE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoDistance: public frc::Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutoDistance(double maxDistance, double power, double minPower, float direction);
	AutoDistance(double maxDistance, double power, double minPower, float direction,
			bool special, double distanceTolerance, double velocityTolerance, double midpointMultiplier);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	void Initialize() override;
	void Execute() override;
	bool IsFinished() override;
	void End() override;
	void Interrupted() override;

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES

	double m_distance;
	double m_power;
	float m_direction;
	double m_distanceTraveled;
	double m_maxPower;
	double m_velocity;
	double m_minPower;
	double m_modPower;
	bool m_specialCase;

	double m_distanceTolerance;
	double m_velocityTolerance;
	double m_midpointMultiplier;

};

#endif
