// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoCurve.h"
#include <cmath>
#include <iostream>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoCurve::AutoCurve(double heading, double power): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::drivePID.get());

	m_heading = heading;
	m_power = -power;


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoCurve::Initialize() {
	Robot::drivePID->ZeroEncoders();
	Robot::drivePID.get()->ZeroYaw();
	Robot::drivePID->SetPIDs(c_turnP, c_turnI, c_turnD);
}

// Called repeatedly when this Command is scheduled to run
void AutoCurve::Execute() {

	Robot::drivePID->DriveCurve(m_power, m_heading);

	std::cout << "Heading Dif:" << (m_heading - Robot::drivePID->GetYaw()) << ", Want: " << fabs(m_heading) << ", At: " << fabs(Robot::drivePID->GetYaw()) <<
					 std::endl;


}

// Make this return true when this Command no longer needs to run execute()
bool AutoCurve::IsFinished() {

	if((fabs(m_heading) <  fabs(Robot::drivePID->GetYaw()))){

			std::cout << " heading is greater than 0" << std::endl;
			return true;
		}
		else{
				return false;
		}

}

// Called once after isFinished returns true
void AutoCurve::End() {
	Robot::drivePID.get()->ArcadeDrive(0,0);
	Robot::drivePID.get()->ZeroEncoders();
	Robot::drivePID.get()->ZeroYaw();
	std::cout << "End" << std::endl;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoCurve::Interrupted() {

}
