// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoDriveWithVision.h"
#include <cmath>
#include <iostream>
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoDriveWithVision::AutoDriveWithVision(double distance, double power, double timeout): frc::Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::drivePID.get());

	m_power = power;
	m_distance = distance;
	m_rotate = 0;
	m_distanceTraveled = 0;

	if(timeout != 0)
	{
		SetTimeout(timeout);
	}
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void AutoDriveWithVision::Initialize() {
	Robot::drivePID->SetPIDs(c_straightP, c_straightI, c_straightD);
	//Robot::drivePID.get()->ZeroYaw();
	//Robot::drivePID.get()->SetDirection(m_heading);
	Robot::drivePID.get()->ZeroEncoders();
	Robot::drivePID.get()->UpdateLimelight();
	m_rotate = 2.5*Robot::drivePID->AdjustWithVision();
	//Robot::drivePID.get()->SetDirection(2.5*m_rotate);
	if(m_rotate > 0 ){
		m_distance = -3.5*Robot::drivePID->AdjustWithVision();
	}
	else{
		m_distance = 3.5*Robot::drivePID->AdjustWithVision();
	}


}

// Called repeatedly when this Command is scheduled to run
void AutoDriveWithVision::Execute() {
	Robot::drivePID->DriveStraight(m_power, m_rotate);

	double rightDist = Robot::drivePID->GetRightEncoder();
	double leftDist = Robot::drivePID->GetLeftEncoder()*(-1);

	if(rightDist < 0 ){
		m_distanceTraveled =  (rightDist+leftDist)/2*(-1);
	}
	else if (rightDist > 0){
		m_distanceTraveled = ((rightDist+leftDist)/2)*(-1);
	}
	else{
		m_distanceTraveled = 0;
	}



	std::cout << "Right: " << rightDist << " Left:" << leftDist <<
	" Distance Traveled: " << m_distanceTraveled <<
	" Set Distance: " << m_distance
	<< " Gyro: " << Robot::drivePID.get()->GetYaw() << std::endl;
}

// Make this return true when this Command no longer needs to run execute()
bool AutoDriveWithVision::IsFinished() {
	if((m_power > 0) && (m_distanceTraveled > m_distance)){
		Robot::drivePID->SetSidePower(-1,-1);
		Wait(.1);
		std::cout << "  1  " << std::endl;
		return true;
	}
	else if((m_power < 0) && (m_distanceTraveled < m_distance)){
		Robot::drivePID->SetSidePower(1,1);
		Wait(.1);
		std::cout << "  2  " << std::endl;
		return true;
	}
	else if(IsTimedOut()){
		std::cout << "  3  " << std::endl;
		//Robot::drivePID->SetSidePower(-1,1);
		Wait(.1);
		return true;
	}
	else{
		return false;
	}
}

// Called once after isFinished returns true
void AutoDriveWithVision::End() {
	Robot::drivePID->ArcadeDrive(0, 0);
	Robot::drivePID.get()->ZeroEncoders();
	//Robot::drivePID.get()->ZeroYaw();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoDriveWithVision::Interrupted() {

}
