// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "LeftScaleAuto2.h"
#include "AutoDistance.h"
#include "AutoCurve.h"
#include "SetKirby.h"
#include "WaveWait.h"
#include "AutoRotate.h"
#include "SetElbow.h"
#include "SetKirbyKlaw.h"
#include "SetKirby.h"
#include "SetElevator.h"
#include "AutoDriveWithVision.h"
#include "SetElevator.h"
#include "AutoDrive.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LeftScaleAuto2::LeftScaleAuto2() {
	//Drive and prepare for scale
	AddParallel(new SetElevator(30));
	AddParallel(new SetElbow(30));
	AddSequential(new AutoDistance(-286, -.75, 0));
	AddParallel(new SetElevator(70));
	AddSequential(new AutoRotate(55));
	AddSequential(new SetElbow(60));

	//Place cube
	AddSequential(new SetKirby(-0.7, 0.5));

	//Back away
	AddParallel(new SetElbow(0));
	AddParallel(new SetElevator(50));
	AddSequential(new AutoDistance(10, 0.7, 55));
	AddParallel(new SetElevator(0));
	AddParallel(new SetElbow(160));
	AddParallel(new AutoRotate(150));
	AddSequential(new SetElevator(0));
	AddParallel(new SetKirbyKlaw(true));

	//Drive and grab to cube 2
	AddSequential(new AutoDrive(-100, -0.4, 150, true));
	AddParallel(new SetKirby(0.5, 0.5));
	AddSequential(new SetKirbyKlaw(false));
	AddSequential(new SetKirby(0.5, 0.25));

	//Drive and prepare for scale
	AddParallel(new SetElevator(70));
	AddParallel(new SetElbow(60));
	AddSequential(new AutoDistance(100, .7, 150));
	AddSequential(new AutoRotate(90));
	AddSequential(new AutoDistance(-20, -0.6, 90));
	AddSequential(new WaveWait(0.5));

	//Place cube
	AddSequential(new SetKirby(-0.5, 0.5));

	//Drive away and drive to cube 3 (runs out of time)
	AddSequential(new AutoDistance(50, 0.8, 178));
	AddSequential(new AutoRotate(140));
	AddParallel(new SetElevator(0));
	AddParallel(new SetElbow(160));
	AddSequential(new AutoDrive(-40, -.4, 140, true));

	AddParallel(new SetKirby(0.5, 0.5));
	AddSequential(new SetKirbyKlaw(false));
	AddSequential(new SetKirby(0.5, 0.75));

	AddSequential(new SetElevator(35));

 }
