// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "LeftScaleSwitchAuto.h"
#include "AutoDrive.h"
#include "AutoDriveTimed.h"
#include "AutoCurve.h"
#include "SetElbow.h"
#include "SetKirby.h"
#include "WaveWait.h"
#include "AutoRotate.h"
#include "SetKirbyKlaw.h"
#include "AutoDistance.h"
#include "AutoDriveWithVisionL.h"
#include "SetElevator.h"

LeftScaleSwitchAuto::LeftScaleSwitchAuto() {
	//Drive and prepare for scale
	AddParallel(new SetElevator(30));
	AddParallel(new SetElbow(30));
	AddSequential(new AutoDistance(-286, -.75, 0));
	AddParallel(new SetElevator(70));
	AddSequential(new AutoRotate(55));
	AddSequential(new SetElbow(60));

	//Place cube
	AddSequential(new SetKirby(-0.5, 0.5));

	//Back away
	AddParallel(new SetElbow(0));
	AddParallel(new SetElevator(50));
	AddSequential(new AutoDistance(10, 0.7, 55));
	AddSequential(new SetKirbyKlaw(true));
	AddParallel(new SetElevator(0));
	AddParallel(new SetElbow(160));
	AddParallel(new AutoRotate(150));

	//Drive and grab to cube 2
	AddSequential(new AutoDrive(-100, -0.4, 150, true));
	AddParallel(new SetKirby(0.5, 0.5));
	AddSequential(new SetKirbyKlaw(false));
	AddSequential(new SetKirby(0.5, 0.25));

	AddSequential(new SetElevator(35));
	AddSequential(new AutoDriveTimed(-.5, 178, .5));
	AddSequential(new SetKirbyKlaw(true));

	AddSequential(new AutoDistance(50, 0.8, 178));
	AddSequential(new AutoRotate(150));
	AddParallel(new SetElevator(0));
	AddParallel(new SetElbow(160));
	AddSequential(new AutoDrive(-40, -.4, 170, true));

	AddParallel(new SetKirby(0.5, 0.5));
	AddSequential(new SetKirbyKlaw(false));
	AddSequential(new SetKirby(0.5, 0.75));

	AddSequential(new SetElevator(35));

 }
