// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "LeftSwitchExchangeAuto.h"
#include "AutoDrive.h"
#include "AutoDriveTimed.h"
#include "AutoCurve.h"
#include "SetElbow.h"
#include "SetKirby.h"
#include "WaveWait.h"
#include "AutoRotate.h"
#include "SetKirbyKlaw.h"
#include "AutoDriveWithVisionL.h"
#include "SetElevator.h"
#include "AutoDistance.h"

LeftSwitchExchangeAuto::LeftSwitchExchangeAuto() {

	//Drive forward to switch
	AddParallel(new SetElbow(145));
	AddSequential(new AutoDistance(-10, -0.8, 0));
	AddSequential(new AutoRotate(-40));
	AddParallel(new SetElevator(35));
	AddSequential(new AutoDistance(-120, -.8, -40));

	//Prepare and place cube

	AddSequential(new AutoRotate(0));
	AddSequential(new AutoDriveTimed(-0.5, 0, .5));
	AddSequential(new SetKirbyKlaw(true));
	AddSequential(new WaveWait(0.25));

	//Back up and drive to cube
	AddParallel(new SetElbow(160));
	AddSequential(new AutoRotate(-40));
	AddParallel(new SetElevator(0));
	AddSequential(new AutoDistance(100, 0.8, -40));
	AddSequential(new AutoRotate(0));

	//Acquire cube
	AddSequential(new AutoDrive(-40, -0.5, 0, true));
	AddParallel(new SetKirby(0.7, 0.5));
	AddSequential(new SetKirbyKlaw(false));
	AddSequential(new SetKirby(0.7, 0.75));

	//Drive to switch
	AddSequential(new AutoRotate(-40));
	AddParallel(new SetElevator(35));
	AddSequential(new AutoDistance(-100, -0.8, -40));

	//Place cube
	AddSequential(new AutoDriveTimed(-0.3, 0, 1.25));
	AddSequential(new SetKirbyKlaw(true));
	AddSequential(new WaveWait(0.25));


 }
