// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "LeftSwitchTimedAuto.h"
#include "AutoDriveTimed.h"
#include "AutoCurve.h"
#include "SetElbow.h"
#include "SetKirby.h"
#include "WaveWait.h"
#include "AutoRotate.h"
#include "SetKirbyKlaw.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LeftSwitchTimedAuto::LeftSwitchTimedAuto() {

	//Drive forward to switch
	AddSequential(new AutoCurve(0.5, -29));
	AddSequential(new AutoDriveTimed(-0.8, 0, 1.));
	AddSequential(new WaveWait(.3));
	//AddSequential(new AutoCurve(0.3, 10));

	//Place cube
	AddSequential(new SetElbow(30));
	AddSequential(new WaveWait(0.25));
	AddSequential(new SetKirby(-0.6, .5));
 }
