// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "ScaleOnlyAuto.h"
#include "AutoDrive.h"
#include "AutoCurve.h"
#include "SetKirby.h"
#include "WaveWait.h"
#include "AutoRotate.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ScaleOnlyAuto::ScaleOnlyAuto() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

	//Drive forward to switch
	AddSequential(new AutoDrive(-50, -0.5, 0));
	AddSequential (new AutoCurve(45, .5));
	AddSequential(new AutoDrive(-150, -0.5, 0));
	AddSequential(new AutoCurve(-42, .5));
	AddSequential(new AutoDrive(-50, -0.5, 0));
	//Add a parallel command to raise elevator
	//AddSequential(new SetKirby(.85, .5));

	//back up to grab new cube
	AddSequential(new AutoDrive(250, 0.5, 0));
	AddSequential(new AutoRotate(40));

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
