// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Z_SetpointCommand.h"


Z_SetpointCommand::Z_SetpointCommand(double setpoint): Command() {
    m_setpoint = setpoint;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
//	Requires(Robot::elevator.get());
}

// Called just before this Command runs the first time
void Z_SetpointCommand::Initialize() {
//    Robot::elevator->Enable();
//    Robot::elevator->SetSetpoint(m_setpoint);
}

// Called repeatedly when this Command is scheduled to run
void Z_SetpointCommand::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool Z_SetpointCommand::IsFinished() {
//    return Robot::elevator->OnTarget();
	return true;
}

// Called once after isFinished returns true
void Z_SetpointCommand::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Z_SetpointCommand::Interrupted() {

}
