// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<WPI_TalonSRX> driveLeft1;
	static std::shared_ptr<WPI_TalonSRX> driveLeft2;
	static std::shared_ptr<WPI_TalonSRX> driveLeft3;
	static std::shared_ptr<frc::SpeedControllerGroup> driveLeftDriveGroup;
	static std::shared_ptr<WPI_TalonSRX> driveRight1;
	static std::shared_ptr<WPI_TalonSRX> driveRight2;
	static std::shared_ptr<WPI_TalonSRX> driveRight3;
	static std::shared_ptr<frc::SpeedControllerGroup> driveRightDriveGroup;
	static std::shared_ptr<frc::DifferentialDrive> driveDiffDrive;
	static std::shared_ptr<frc::Encoder> driveLeftEncoder;
	static std::shared_ptr<frc::Encoder> driveRightEncoder;
	static std::shared_ptr<frc::Solenoid> driveShifter;
	static std::shared_ptr<WPI_TalonSRX> kirbyKirbyRight;
	static std::shared_ptr<WPI_TalonSRX> kirbyKirbyLeft;
	static std::shared_ptr<frc::DigitalInput> kirbyKirbyFull;
	static std::shared_ptr<frc::Solenoid> kirbyKirbyKlaw;
	static std::shared_ptr<frc::Solenoid> ironCrossDeployCross;
	static std::shared_ptr<frc::Solenoid> ironCrossDeployTRexArms;
	static std::shared_ptr<frc::Encoder> elevatorElevatorEncoder;
	static std::shared_ptr<WPI_TalonSRX> elevatorElevatorRight;
	static std::shared_ptr<WPI_TalonSRX> elevatorElevatorLeft;
	static std::shared_ptr<frc::DigitalInput> elevatorElevatorZero;
	static std::shared_ptr<frc::SpeedControllerGroup> elevatorLiftMotors;
	static std::shared_ptr<WPI_TalonSRX> elbowElbowRight;
	static std::shared_ptr<WPI_TalonSRX> elbowElbowLeft;
	static std::shared_ptr<frc::SpeedControllerGroup> elbowElbowRotate;
	static std::shared_ptr<frc::DigitalInput> elbowElbowZero;
	static std::shared_ptr<frc::Encoder> elbowElbowPosition;
	static std::shared_ptr<WPI_TalonSRX> drivePIDLeft1;
	static std::shared_ptr<WPI_TalonSRX> drivePIDLeft2;
	static std::shared_ptr<WPI_TalonSRX> drivePIDLeft3;
	static std::shared_ptr<frc::SpeedControllerGroup> drivePIDLeftDriveGroup;
	static std::shared_ptr<WPI_TalonSRX> drivePIDRight1;
	static std::shared_ptr<WPI_TalonSRX> drivePIDRight2;
	static std::shared_ptr<WPI_TalonSRX> drivePIDRight3;
	static std::shared_ptr<frc::SpeedControllerGroup> drivePIDRightDriveGroup;
	static std::shared_ptr<frc::DifferentialDrive> drivePIDDiffDrive;
	static std::shared_ptr<frc::Encoder> drivePIDLeftEncoder;
	static std::shared_ptr<frc::Encoder> drivePIDRightEncoder;
	static std::shared_ptr<frc::Solenoid> drivePIDShifter;
	static std::shared_ptr<Compressor> compressorSubsystemCompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
